Rewrite
cobwebdev/cssheet pull request #14
Opened 2021-09-01 18:09 UTC by aa2006

The rewrite branch now has all the features of the main branch.

2021-09-02 10:52 UTC, whyadamsalt requested changes

2021-09-02 10:52 UTC, ghost commented on README.md
> -* Please be aware that our CDN automatically updates, however it may take up to 2 hours for the cache to clear on the CDN.
This section here should remain on the GitHub readme

2021-09-02 10:52 UTC, ghost commented on package.json
> +  "version": "0.0.0",
This is version v1.3.0 of CSSheet

2021-09-02 10:52 UTC, ghost commented on README.md
> +See our [documentation](#)
There is no documentation.md file, please create one and write out the full documentation before merging,

2021-09-09 09:36 UTC, whyadamsalt commented
When you have completed the requested changes please contact me on Discord for me to re-review the PR, thank you.

2021-09-19 23:11 UTC, ReasonablySelenium commented
Ok to merge.

2021-09-19 23:12 UTC, ReasonablySelenium approved these changes

2021-09-20 15:12 UTC, merged